### ISSUE TITLE
~/Bible/helm-bible/esv-bible-text.txt is missing

### ISSUE THREAD

**Issue by DarkBuffalo** [AndyHolt/helm-bible#2]
Hi,
your code is cool but 
the file ~/Bible/helm-bible/esv-bible-text.txt  is missing, is it possible to know the syntax of this one?

**Comment by AndyHolt** [comment]
Hi, I have a script [Erasmus/save-bible-to-ref-text.sh](https://github.com/AndyHolt/Erasmus/blob/c6e7d7096b5ca3d31548a8d86b6273b7fd109f9c/save-bible-to-ref-text.sh) that generates the data file, though it may need updating to run properly. I've been meaning to get that working again so I can add more versions to my search database, but what I already have works well enough to have not yet got round to improving it. Contributions welcome.

The format of the file is simply the Bible book name followed by chapter number:verse number and the text of the verse. Each verse on a single line, a newline for each verse:

```
Genesis 1:1: In the beginning, God created the heavens and the earth.
Genesis 1:2: The earth was without form and void, and darkness was over the face of the deep. And the Spirit of God was hovering over the face of the waters.
Genesis 1:3: And God said, “Let there be light”, and there was light.
Genesis 1:4: And God saw that the light was good. And God separated the light from the darkness.
Genesis 1:5: God called the light Day, and the darkness he called Night. And there was evening and there was morning, the first day.
```

**Comment by DarkBuffalo** [comment]
Thanks. good job.
